# core/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers
from .views import (
    LoginAPIView,
    PoliceOfficeAdminViewSet,
    ReportViewSet,
    MessageViewSet,
    CheckpointViewSet,
    MediaViewSet,
    TopLocationsAPIView,
    AdminMapAPIView,
    AnalyticsUpdateAPIView,
)
from .views.analytics import (
    AnalyticsOverviewSummaryAPIView,
    LocationHotspotsAPIView,
    CategoryConcentrationAPIView,
    AnalyticsExportAPIView,
)
from .views.reports import (
    ResolvedCasesAPIView,
    ResolvedCasesExportAPIView,
    SingleReportExportAPIView,
)


# Create a router instance
router = DefaultRouter()
# Register the Police Office ViewSet under the admin/ route
router.register(r'admin/police-offices', PoliceOfficeAdminViewSet, basename='police-office')
# Register the Report ViewSet
router.register(r'reports', ReportViewSet, basename='report') 
# Register the Checkpoint ViewSet
router.register(r'checkpoints', CheckpointViewSet, basename='checkpoint') 
# Register the Media ViewSet
router.register(r'media', MediaViewSet, basename='media')

# Create the nested router for messages
reports_router = routers.NestedSimpleRouter(router, r'reports', lookup='report')
# Register the messages endpoint under the reports
reports_router.register(r'messages', MessageViewSet, basename='report-messages')

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view(), name='login'),
    path('reports/summary/top-locations/', TopLocationsAPIView.as_view(), name='top-locations'),
    
    # Admin Active Map API URL
    path('admin/map/data/', AdminMapAPIView.as_view(), name='admin-map-data'),
    
    # Analytics Update Trigger
    path('admin/analytics/update/', AnalyticsUpdateAPIView.as_view(), name='analytics-update'),

    # Analytics Data Endpoints
    path('analytics/summary/overview/', AnalyticsOverviewSummaryAPIView.as_view()),

    # Hotspots and Export Endpoints
    path('analytics/hotspots/locations/', LocationHotspotsAPIView.as_view()),

    # Hotspots and Export Endpoints
    path('analytics/hotspots/categories/', CategoryConcentrationAPIView.as_view()),

    # Hotspots and Export Endpoints
    path('analytics/export/', AnalyticsExportAPIView.as_view()),

    # Resolved Cases Endpoints
    path('reports/resolved/', ResolvedCasesAPIView.as_view()),

    # Resolved Cases Export Endpoints
    path('reports/resolved/export/', ResolvedCasesExportAPIView.as_view()),
    path('reports/<uuid:report_id>/export/', SingleReportExportAPIView.as_view()),

    # Include all URLs generated by the router
    # INCLUDE BOTH ROUTER URLS UNDER THE MAIN API PATH
    path('', include(router.urls)),           # Includes /reports/ and /admin/police-offices/
    path('', include(reports_router.urls)),   
]