# core/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers
from .views import (
    LoginAPIView, 
    PoliceOfficeAdminViewSet, 
    ReportViewSet, 
    MessageViewSet, 
    CheckpointViewSet,
    MediaViewSet
)

# Create a router instance
router = DefaultRouter()
# Register the Police Office ViewSet under the admin/ route
router.register(r'admin/police-offices', PoliceOfficeAdminViewSet, basename='police-office')
# Register the Report ViewSet
router.register(r'reports', ReportViewSet, basename='report') 
# Register the Checkpoint ViewSet
router.register(r'checkpoints', CheckpointViewSet, basename='checkpoint') 
# Register the Media ViewSet
router.register(r'media', MediaViewSet, basename='media')

# Create the nested router for messages
reports_router = routers.NestedSimpleRouter(router, r'reports', lookup='report')
# Register the messages endpoint under the reports
reports_router.register(r'messages', MessageViewSet, basename='report-messages')

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view(), name='login'),
    # Include all URLs generated by the router
   # INCLUDE BOTH ROUTER URLS UNDER THE MAIN API PATH
    path('', include(router.urls)),           # Includes /reports/ and /admin/police-offices/
    path('', include(reports_router.urls)),   # <-- THIS LINE WAS MISSING IN YOUR ORIGINAL LIST.
]